server:
  port: 8084

spring:
  application:
    name: payroll-service
  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payroll_db}
    username: ${SPRING_DATASOURCE_USERNAME:workhub}
    password: ${SPRING_DATASOURCE_PASSWORD:workhub}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false # À passer à true uniquement pour le debug

  flyway:
    enabled: true


  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    # On configure aussi le consumer au cas où tu doives écouter EmployeeService
    consumer:
      group-id: payroll-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.workhub.*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics