server:
  port: 8081

spring:
  application:
    name: org-service

  datasource:
    url: jdbc:postgresql://localhost:5432/org_db
    username: workhub
    password: workhub

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://feasible-vervet-9.clerk.accounts.dev/.well-known/jwks.json

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info