version: '3.8'

services:
  recruitment-service:
    build: ./recruitment-service
    container_name: workhub-recruitment-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/recruitment_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - workhub
    depends_on:
      - postgres
      - kafka

  ai-service:
    build: ./ai-service
    container_name: workhub-ai-service
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MINIO_ENDPOINT=http://minio:9000
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - workhub
    depends_on:
      - kafka
      - minio

networks:
  workhub:
    external: true
