server:
  port: 8086

spring:
  application:
    name: document-service

  datasource:
    url: jdbc:postgresql://localhost:5432/document_db
    username: workhub
    password: workhub

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info